# Generated by Django 4.0 on 2025-11-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='商品名')),
                ('content', models.TextField(verbose_name='商品説明')),
                ('category', models.CharField(choices=[('食料品', '食料品'), ('日用品', '日用品'), ('生活用品', '生活用品')], max_length=50, verbose_name='カテゴリ')),
            ],
        ),
    ]
