# Generated by Django 4.0 on 2025-11-17 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypost',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='投稿日時'),
            preserve_default=False,
        ),
    ]
