# Generated by Django 4.0 on 2025-11-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_control', '0002_inventorypost_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypost',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='在庫数'),
        ),
    ]
